name: cnns
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - pip:
    - matplotlib
    - numpy
    - pandas
    - tensorflow
    - opencv-python
    - tensorflow-datasets
    - mplhep
    - seaborn
    - git+git://github.com/google/qkeras.git#egg=qkeras